# Generated by Django 4.2.7 on 2023-11-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DragonAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('digestion_period_hours', models.IntegerField()),
                ('herbivore', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('park_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DragonFed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dragon_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('park_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DragonLocationUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('dragon_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('park_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DragonRemoved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dragon_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('park_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePerformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('park_id', models.IntegerField()),
            ],
        ),
    ]
