# Generated by Django 4.2.7 on 2023-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonadded',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
