# Generated by Django 4.2.7 on 2023-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0002_alter_dragonadded_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragonadded',
            name='time',
            field=models.TimeField(),
        ),
    ]
