# Generated by Django 4.2.7 on 2023-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoos', '0003_alter_dragonadded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragonfed',
            name='last_meal_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
